version: 2

project_name: fusebox

builds:
  - id: fusebox-darwin
    binary: fusebox
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - embed_server
    hooks:
      pre:
        - cmd: sh -c "GOOS=linux GOARCH=arm64 go build -o internal/embed/fusebox-linux-arm64 . && GOOS=linux GOARCH=amd64 go build -o internal/embed/fusebox-linux-amd64 ."

  - id: fusebox-linux
    binary: fusebox
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: binaries
    format: binary
    name_template: "fusebox-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: lableaks
    name: fusebox
  extra_files:
    - glob: rootfs/fusebox-rootfs-*.tar.gz

changelog:
  sort: asc
